apiVersion: 1

deleteDatasources:
  - name: UMH TimescaleDB
    orgId: 1

datasources:
  - name: UMH TimescaleDB
    uid: umh-timescaledb
    type: grafana-postgresql-datasource
    url: timescaledb:5432
    database: umh
    user: grafanareader
    secureJsonData:
      password: changeme
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
    editable: true
